# Generated by Django 4.0.10 on 2024-03-14 05:09

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(null=True, upload_to=user.models.user_image_file_path),
        ),
    ]
